### ISSUE TITLE
The nakama server will be crashed if you try to join nonexistent group

### ISSUE THREAD

**Issue by Suvitruf** [heroiclabs/nakama#243]
The nakama server will be crashed if you try to join nonexistent group.

## Logs
```
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: panic: runtime error: index out of range
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: goroutine 1188 [running]:
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: github.com/heroiclabs/nakama/server.JoinGroup(0xc4202bc9c0, 0xc4203be5a0, 0x3f4a005cd4f4451f, 0xa0a58dc436bda3a3, 0x2e4931d0e696d5ca, 0x484649f533a0686, 0xc4200727e0, 0xc4207412e8)
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: #011/Users/novabyte/go/src/github.com/heroiclabs/nakama/server/core_group.go:304 +0x1eba
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: github.com/heroiclabs/nakama/server.(*ApiServer).JoinGroup(0xc420147c80, 0x10e2460, 0xc42098c150, 0xc4206d7cb0, 0xc420147c80, 0x2, 0x2)
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: #011/Users/novabyte/go/src/github.com/heroiclabs/nakama/server/api_group.go:116 +0x1bc
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: github.com/heroiclabs/nakama/api._Nakama_JoinGroup_Handler.func1(0x10e2460, 0xc42098c150, 0xf2c0c0, 0xc4206d7cb0, 0x2, 0x16dc7e0, 0x0, 0x0)
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: #011/Users/novabyte/go/src/github.com/heroiclabs/nakama/api/api.pb.go:5653 +0x89
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: github.com/heroiclabs/nakama/server.apiInterceptorFunc.func1(0x10e2460, 0xc42098c150, 0xf2c0c0, 0xc4206d7cb0, 0xc420814ee0, 0xc420814f00, 0xe6f060, 0x1700098, 0xfa3980, 0xc420752800)
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: #011/Users/novabyte/go/src/github.com/heroiclabs/nakama/server/api.go:301 +0xb6d
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: github.com/heroiclabs/nakama/api._Nakama_JoinGroup_Handler(0xfbad40, 0xc420147c80, 0x10e2460, 0xc4206d7c20, 0xc420143030, 0xc42017e040, 0x0, 0x0, 0xc420752800, 0xc4207a8b00)
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: #011/Users/novabyte/go/src/github.com/heroiclabs/nakama/api/api.pb.go:5655 +0x167
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4203808c0, 0x10ea4a0, 0xc42062a000, 0xc420752800, 0xc420565290, 0x16d2ac0, 0x0, 0x0, 0x0)
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: #011/Users/novabyte/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1011 +0x4fc
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4203808c0, 0x10ea4a0, 0xc42062a000, 0xc420752800, 0x0)
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: #011/Users/novabyte/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1249 +0x1318
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42067a1e0, 0xc4203808c0, 0x10ea4a0, 0xc42062a000, 0xc420752800)
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: #011/Users/novabyte/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:680 +0x9f
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: created by github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
Sep 13 14:22:54 unnynet-nakama-1 nakama[32528]: #011/Users/novabyte/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:678 +0xa1
Sep 13 14:22:54 unnynet-nakama-1 systemd[1]: nakama.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 13 14:22:54 unnynet-nakama-1 systemd[1]: nakama.service: Unit entered failed state.
Sep 13 14:22:54 unnynet-nakama-1 systemd[1]: nakama.service: Failed with result 'exit-code'.
```

## Steps to Reproduce

1. I don't think, that it's related to JS. But using JS client lib try to join nonexistent group: `await this.client.joinGroup(this.currentSession, "1f45f4d4-5c00-4a3f-a3a3-bd36c48da5a0")`
2. Nakama server will be crashed.

**Comment by mofirouz** [comment]
Thanks for reporting this. This is now fixed with commit ba646e73923e0b9a4351c30087edace242c540e5 and will be in the upcoming release.
