### ISSUE TITLE
Nakama crashed on storage request

### ISSUE THREAD

**Issue by Suvitruf** [heroiclabs/nakama#261]
**Nakama version**: 2.1.2.

JavaScript client library.
We are using methods:
`client.writeStorageObjects`
`client.readStorageObjects`
`client.listStorageObjects`
`client.deleteStorageObjects`

Nakama.log:

```
{
    "level": "error",
    "ts": "2018-11-07T11:16:00.991Z",
    "msg": "Could not list storage.",
    "error": "context canceled",
    "collection": "1f45f4d4-5c00-4a3f-a3a3-bd36c48da5a0",
    "limit": 100,
    "cursor": "",
    "stacktrace": "github.com/heroiclabs/nakama/server.StorageListObjectsUser.func1\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/server/core_storage.go:198\ngithub.com/heroiclabs/nakama/server.ExecuteRetryable\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/server/db.go:71\ngithub.com/heroiclabs/nakama/server.StorageListObjectsUser\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/server/core_storage.go:183\ngithub.com/heroiclabs/nakama/server.StorageListObjects\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/server/core_storage.go:68\ngithub.com/heroiclabs/nakama/server.(*ApiServer).ListStorageObjects\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/server/api_storage.go:81\ngithub.com/heroiclabs/nakama/apigrpc._Nakama_ListStorageObjects_Handler.func1\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.go:1666\ngithub.com/heroiclabs/nakama/server.StartApiServer.func1\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/server/api.go:87\ngithub.com/heroiclabs/nakama/apigrpc._Nakama_ListStorageObjects_Handler\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.go:1668\ngithub.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).processUnaryRPC\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1011\ngithub.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).handleStream\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1249\ngithub.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/home/unnynet/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:680"
}
```

Ubuntu syslog:

```
Nov  7 11:16:00  nakama[18810]: panic: runtime error: invalid memory address or nil pointer dereference
Nov  7 11:16:00  nakama[18810]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1259f83]
Nov  7 11:16:00  nakama[18810]: goroutine 4635651 [running]:
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/server.ExecuteRetryable(0xc0021ed280, 0x16ad7e0, 0x99)
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/server/db.go:72 +0x93
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/server.StorageListObjectsUser(0x1a73140, 0xc0021afd10, 0xc000435200, 0xc00040a3c0, 0x4237a5c5d184b200, 0x4398360$
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/server/core_storage.go:183 +0x2e1
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/server.StorageListObjects(0x1a73140, 0xc0021afd10, 0xc000435200, 0xc00040a3c0, 0x94237a5c5d184b2, 0x6e43983608ea$
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/server/core_storage.go:68 +0x23e
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/server.(*ApiServer).ListStorageObjects(0xc000fc8990, 0x1a73140, 0xc0021afd10, 0xc0035fe780, 0xc000fc8990, 0xc001$
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/server/api_storage.go:81 +0x2f5
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/apigrpc._Nakama_ListStorageObjects_Handler.func1(0x1a73140, 0xc0021afd10, 0x15faf20, 0xc0035fe780, 0xc0021afce0,$
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.go:1666 +0x89
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/server.StartApiServer.func1(0x1a73140, 0xc0021afad0, 0x15faf20, 0xc0035fe780, 0xc0013b4d00, 0xc0013b4d20, 0x14f5$
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/server/api.go:87 +0xe9
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/apigrpc._Nakama_ListStorageObjects_Handler(0x165d940, 0xc000fc8990, 0x1a73140, 0xc0021afad0, 0xc001192b60, 0xc00$
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.go:1668 +0x158
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002708c0, 0x1a7b960, 0xc001274200, 0xc000977900, 0xc$
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1011 +0x4cd
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0002708c0, 0x1a7b960, 0xc001274200, 0xc000977900, 0x0)
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1249 +0x1308
Nov  7 11:16:00  nakama[18810]: github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0011f2080, 0xc0002708c0, 0x1a7b960, 0xc001274200$
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:680 +0x9f
Nov  7 11:16:00  nakama[18810]: created by github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
Nov  7 11:16:00  nakama[18810]: #011/home/unnynet/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:678 +0xa1
Nov  7 11:16:01  systemd[1]: nakama.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov  7 11:16:01  systemd[1]: nakama.service: Unit entered failed state.
Nov  7 11:16:01  systemd[1]: nakama.service: Failed with result 'exit-code'.
```

**Comment by zyro** [comment]
Thanks for the report! This is resolved in 2614febceba50070a97ed796ed94f3877b7737da and will be part of the next release.
