### ISSUE TITLE
tournament end, panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ZhangGuangxu** [heroiclabs/nakama#281]
## Description
tournament end, panic: runtime error: index out of range

## Steps to Reproduce
tournament end.   Just happened one time for now.

## Context
nakama-js

## Your Environment
- Nakama: 2.0.0+dev, commit fc37ea85bc42e9177c530a67ff45527da169a8a7
- Operating System and version: Ubuntu 16.04.5 LTS

## Crash stacktrack

```
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: panic: runtime error: index out of range
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: goroutine 86843979 [running]:
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr.(*Expression).nextDayOfMonth(0xc000590620, 0x2315b7, 0xed3b250c0, 0x0, 0x1, 0xa69cfa, 0x1)
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr/cronexpr_next.go:114 +0x255
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr.(*Expression).nextHour(0xc000590620, 0x2315b7, 0xed3b250c0, 0x0, 0x1, 0xc1ac4016c0, 0xa69cfa)
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr/cronexpr_next.go:129 +0x238
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr.(*Expression).nextMinute(0xc000590620, 0x2315b7, 0xed3b250c0, 0x0, 0x1, 0x0, 0xc1ac401750)
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr/cronexpr_next.go:150 +0x266
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr.(*Expression).nextSecond(0xc000590620, 0x2315b7, 0xed3b250c0, 0x0, 0x0, 0x5, 0x30)
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr/cronexpr_next.go:174 +0x29c
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr.(*Expression).Next(0xc000590620, 0x2315b7, 0xed3b250c0, 0x0, 0x0, 0x2, 0x0)
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr/cronexpr.go:234 +0x491
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr.(*Expression).NextN(0xc000590620, 0x2315b7, 0xed3b250c0, 0x0, 0x2, 0xc155581c20, 0x2, 0x2)
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/vendor/github.com/gorhill/cronexpr/cronexpr.go:252 +0xbc
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/server.calculateTournamentDeadlines(0xc0005ee790, 0x2315b7, 0xed3b250c0, 0x0, 0x5c2059c0, 0x5c299440, 0x5c299440)
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/server/core_tournament.go:467 +0x108
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/server.(*LocalLeaderboardScheduler).Update(0xc0000b88c0)
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/server/leaderboard_scheduler.go:157 +0x554
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/server.(*LocalLeaderboardScheduler).invokeEndActiveElapse(0xc0000b88c0, 0x0, 0xed3b250c0, 0x0)
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/server/leaderboard_scheduler.go:262 +0x9f
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: github.com/heroiclabs/nakama/server.(*LocalLeaderboardScheduler).Update.func1()
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /Users/zhangguangxu/code/nakama-hero-master/src/github.com/heroiclabs/nakama/server/leaderboard_scheduler.go:233 +0x78
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]: created by time.goFunc
Dec 24 04:00:00 ip-172-31-16-21 run.sh[7895]:         /usr/local/Cellar/go/1.11.1/libexec/src/time/sleep.go:172 +0x44
```

**Comment by mofirouz** [comment]
Thanks a lot! We'll take a look and see if we can include a fix in the upcoming 2.3.0.

**Comment by novabyte** [comment]
@ZhangGuangxu can you give me more information on the environment you run the server in:
* Do you use UTC timezone configuration on the server?
* Does the server run NTP or another timesync daemon that reduces clock drift?
* When was the last time the timezone database updated on your Ubuntu machine? i.e. tzdata
