### ISSUE TITLE
Segfault with paging backwards with leaderboard cursors

### ISSUE THREAD

**Issue by tkou-nakama** [heroiclabs/nakama#290]
## Description

Changing pages from page 2 to page 1 causes segmentation violation.

```
nakama         | panic: runtime error: invalid memory address or nil pointer dereference
nakama         | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1273d86]
nakama         |
nakama         | goroutine 86 [running]:
nakama         | github.com/heroiclabs/nakama/server.LeaderboardRecordsList(0x1aea040, 0xc001312d80, 0xc0003f8cc0, 0xc000112180, 0x1af25a0, 0xc00057e120, 0x1aeee80, 0xc00036fb80, 0xc0012efed8, 0x6, ...)
nakama         |        /go/src/github.com/heroiclabs/nakama/server/core_leaderboard.go:205 +0x2856
nakama         | github.com/heroiclabs/nakama/server.(*ApiServer).ListLeaderboardRecords(0xc0001826c0, 0x1aea040, 0xc001312d80, 0xc000abb3e0, 0xc0001826c0, 0xc0012f7e00, 0x0)
nakama         |        /go/src/github.com/heroiclabs/nakama/server/api_leaderboard.go:148 +0x281
nakama         | github.com/heroiclabs/nakama/apigrpc._Nakama_ListLeaderboardRecords_Handler.func1(0x1aea040, 0xc001312d80, 0x165d540, 0xc000abb3e0, 0xc001312d50, 0x165d540, 0xc000abb3e0, 0xc0012f7de0)
nakama         |        /go/src/github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.go:1600 +0x89
nakama         | github.com/heroiclabs/nakama/server.StartApiServer.func1(0x1aea040, 0xc001312b70, 0x165d540, 0xc000abb3e0, 0xc0012f7de0, 0xc0012f7e00, 0x154f400, 0x25f09b8, 0x16a3100, 0xc000e62b00)
nakama         |        /go/src/github.com/heroiclabs/nakama/server/api.go:88 +0xe9
nakama         | github.com/heroiclabs/nakama/apigrpc._Nakama_ListLeaderboardRecords_Handler(0x16c0080, 0xc0001826c0, 0x1aea040, 0xc001312b70, 0xc001334500, 0xc000f0ab00, 0x0, 0x0, 0xc001338160, 0x157)
nakama         |        /go/src/github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.go:1602 +0x158
nakama         | github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000495c80, 0x1af2a20, 0xc000b2f680, 0xc000e62b00, 0xc000ee7830, 0x254a368, 0x0, 0x0, 0x0)
nakama         |        /go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:966 +0x4a2
nakama         | github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000495c80, 0x1af2a20, 0xc000b2f680, 0xc000e62b00, 0x0)
nakama         |        /go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1245 +0xd61
nakama         | github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000efe7c0, 0xc000495c80, 0x1af2a20, 0xc000b2f680, 0xc000e62b00)
nakama         |        /go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:685 +0x9f
nakama         | created by github.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
nakama         |        /go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:683 +0xa1
```

## Steps to Reproduce

1. Call Client.ListLeaderboardRecordsAsync with cursor pointing to the second page
2. Call Client.ListLeaderboardRecordsAsync with cursor pointing to the first page, received from previous step.

First page is shown.

## Actual Result

Segmentation violation on the server.

## Context

- [x] Unity
- [ ] Unreal
- [ ] Other

## Your Environment

- Nakama: 2.3.1
- Cockroach: v2.1.3
- Operating System and version: Windows 10 Pro

**Comment by zyro** [comment]
Fixed in 68c02ba16b92de273455ea0cb4929aedc8a441c8 and will be part of the next release.
