### ISSUE TITLE
[Bug]: Error is thrown after matchmaking

### ISSUE THREAD

**Issue by MWFIAE** [heroiclabs/nakama#552]
## Description
Using nakama 3.1 the following code doesn't work and causes a runtime error/panic

## Steps to Reproduce
1. following coding:
```
function MatchmakerMatched(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, matches: nkruntime.MatchmakerResult[]) {
    logger.debug("Making Match");
    let setupState = {
        playerA: JSON.stringify(matches[0].presence),
        playerB: JSON.stringify(matches[1].presence),
    };
    const matchId = nk.matchCreate("matchhandler", setupState);
    logger.info(matchId);
    return matchId;
}

let InitModule: nkruntime.InitModule = function (ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, initializer: nkruntime.Initializer) {
    initializer.registerMatch("matchhandler", {
        matchInit,
        matchJoin,
        matchJoinAttempt,
        matchLeave,
        matchLoop,
        matchTerminate,
    });
    initializer.registerMatchmakerMatched(MatchmakerMatched);
};
```
2. Search a match with 2 or more clients to trigger the matchmaker.

## Expected Result
Matchhandler should be called and the match should proceed normally.

## Actual Result
The MatchmakerMatched function is not called (no "Making Match" output in console). Instead following error message is thrown:
```
nakama         | panic: runtime error: invalid memory address or nil pointer dereference
nakama         | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17e6238]
nakama         |
nakama         | goroutine 75 [running]:
nakama         | github.com/heroiclabs/nakama/v3/server.(*RuntimeJS).invokeFunction(0xc000b19b00, 0x6, 0x1d38090, 0x11, 0x0, 0xc0018a6b40, 0x4, 0x4, 0x0, 0x0, ...)
nakama         |        github.com/heroiclabs/nakama/v3/server/runtime_javascript.go:434 +0x78
nakama         | github.com/heroiclabs/nakama/v3/server.(*RuntimeJS).InvokeFunction(0xc000b19b00, 0x6, 0x1d38090, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
nakama         |        github.com/heroiclabs/nakama/v3/server/runtime_javascript.go:420 +0x391
nakama         | github.com/heroiclabs/nakama/v3/server.(*RuntimeProviderJS).MatchmakerMatched(0xc000024000, 0x20a2be0, 0xc000042028, 0xc00184c590, 0x2, 0x2, 0x1b36040, 0x0, 0xc001014930, 0xc0000ffbd8, ...)
nakama         |        github.com/heroiclabs/nakama/v3/server/runtime_javascript.go:1535 +0xb8c
nakama         | github.com/heroiclabs/nakama/v3/server.NewRuntimeProviderJS.func1.136(0x20a2be0, 0xc000042028, 0xc00184c590, 0x2, 0x2, 0x1, 0x1, 0x2, 0x1, 0xc0012054a0)
nakama         |        github.com/heroiclabs/nakama/v3/server/runtime_javascript.go:1365 +0x66
nakama         | github.com/heroiclabs/nakama/v3/server.(*LocalMatchmaker).process(0xc000228280)
nakama         |        github.com/heroiclabs/nakama/v3/server/matchmaker.go:373 +0x2eb8
nakama         | github.com/heroiclabs/nakama/v3/server.NewLocalMatchmaker.func1(0x20b9cc0, 0xc0004fd900, 0x20a2ba0, 0xc00019cc00, 0xc000228280)
nakama         |        github.com/heroiclabs/nakama/v3/server/matchmaker.go:179 +0x85
nakama         | created by github.com/heroiclabs/nakama/v3/server.NewLocalMatchmaker
nakama         |        github.com/heroiclabs/nakama/v3/server/matchmaker.go:172 +0x4e5
```

## Context
- [x ] Unity

## Your Environment
- Nakama: 3.1.0
- Database: cockroachdb CCL v19.2.5 @ 2020/03/16 18:27:12 (go1.12.12)
- Environment name and version: Docker
- Operating System and version: Windows 10 pro

**Comment by sesposito** [comment]
Thank you for opening this issue @MWFIAE, this is resoved by #553.
