### ISSUE TITLE
Error when using afterDeleteFriends hook

### ISSUE THREAD

**Issue by petja32** [heroiclabs/nakama#572]
## Description
Error thrown when using afterDeleteFriends hook when implemented using TypeScript.

## Steps to Reproduce
1. Add a afterDeleteFriends hook
2. Call DeleteFriends API

Example of hook:
```
const afterDeleteFriends: nkruntime.AfterHookFunction<
  void,
  nkruntime.DeleteFriendsRequest
> = function (
  ctx: nkruntime.Context,
  logger: nkruntime.Logger,
  nk: nkruntime.Nakama,
  outPayload: void,
  inPayload: nkruntime.DeleteFriendsRequest
) {
  logger.info('Goodbye my friend');

  return null;
};

let InitModule: nkruntime.InitModule = function (
  ctx: nkruntime.Context,
  logger: nkruntime.Logger,
  nk: nkruntime.Nakama,
  initializer: nkruntime.Initializer
) {
  initializer.registerAfterDeleteFriends(afterDeleteFriends);
};
```

## Expected Result
The friend request is deleted, the hook is called and no error is thrown.

## Actual Result
The friend request is deleted but the hook is never called and an Error is thrown with stacktrace in logs.

```
panic: interface conversion: interface {} is nil, not string

goroutine 443 [running]:
github.com/heroiclabs/nakama/v3/server.(*ApiServer).DeleteFriends(0xc0002f3360, 0x207d100, 0xc0005c1050, 0xc001268540, 0x0, 0x0, 0x0)
        github.com/heroiclabs/nakama/v3/server/api_friend.go:246 +0x1173
reflect.Value.call(0xc0009f0700, 0xc000010d78, 0x13, 0x1c0450f, 0x4, 0xc000adc1e0, 0x3, 0x3, 0x7fd64050b950, 0xc001268540, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0009f0700, 0xc000010d78, 0x13, 0xc000adc1e0, 0x3, 0x3, 0xc0005c1050, 0x0, 0x0)
        reflect/value.go:337 +0xb9
github.com/heroiclabs/nakama/v3/server.(*ConsoleServer).CallApiEndpoint(0xc000151340, 0x207d100, 0xc000f09aa0, 0xc000a10e40, 0xc000151340, 0x1abf7c0, 0xc000552000)
        github.com/heroiclabs/nakama/v3/server/console_api_explorer.go:86 +0x845
github.com/heroiclabs/nakama/v3/console._Console_CallApiEndpoint_Handler.func1(0x207d100, 0xc000f09aa0, 0x1b23260, 0xc000a10e40, 0xc000552090, 0x1, 0x207d100, 0xc000f09aa0)
        github.com/heroiclabs/nakama/v3/console/console_grpc.pb.go:857 +0x89
github.com/heroiclabs/nakama/v3/server.consoleInterceptorFunc.func1(0x207d100, 0xc000f09aa0, 0x1b23260, 0xc000a10e40, 0xc0009e2440, 0xc0005bb2d8, 0xc0005c8ba0, 0x9d4c86, 0x1b36d80, 0xc000f09830)
        github.com/heroiclabs/nakama/v3/server/console.go:368 +0x249
github.com/heroiclabs/nakama/v3/console._Console_CallApiEndpoint_Handler(0x1be8180, 0xc000151340, 0x207d100, 0xc000f09830, 0xc000a10de0, 0xc000d0c240, 0x207d100, 0xc000f09830, 0xc0005ec730, 0x4f)
        github.com/heroiclabs/nakama/v3/console/console_grpc.pb.go:859 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004e2540, 0x208af18, 0xc0005c2180, 0xc000cec700, 0xc0003b8fc0, 0x28430a8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.33.1/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0004e2540, 0x208af18, 0xc0005c2180, 0xc000cec700, 0x0)
        google.golang.org/grpc@v1.33.1/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005ea020, 0xc0004e2540, 0x208af18, 0xc0005c2180, 0xc000cec700)
        google.golang.org/grpc@v1.33.1/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.33.1/server.go:869 +0x1fd
```

## Context
- [ ] Unity
- [ ] Unreal
- [ x ] Other

## Your Environment
- Nakama: 3.1.2
- Database: 12.3
- Environment: Local
- Operating System and version: Windows 10 2004

**Comment by zyro** [comment]
Fixed in f721c5e6617f7888d7cd42a8933f90c05dbd955f and will be part of the next release.
