### ISSUE TITLE
Panic when executing the `nk.matchGet` method on the server

### ISSUE THREAD

**Issue by Meneleus** [heroiclabs/nakama#610]
## Description
Panic when executing the `nk.matchGet` method on the server

## Steps to Reproduce
1. In the `registerAfterAuthenticateEmail` method
2. Execute: 
```
try {
  const match = nk.matchGet(matchState.uid);
} catch (error) {
  logger.debug(`Error: ${JSON.stringify(error)}`);
}
```
With a well formatted match uid
3. You'll get a panic.

## Expected Result
An exception is thrown since the match id is not active.

## Actual Result
```
nakama_1       | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
nakama_1       |        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
nakama_1       |        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
nakama_1       |        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
nakama_1       |        panic: runtime error: invalid memory address or nil pointer dereference
nakama_1       | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x199cb2a]
nakama_1       |
nakama_1       | goroutine 106 [running]:
nakama_1       | github.com/dop251/goja.AssertFunction.func1.1(0xc0010ca9d0)
nakama_1       |        github.com/dop251/goja@v0.0.0-20210406175830-1b11a6af686d/runtime.go:2090 +0x95
nakama_1       | panic(0x1b4eac0, 0x2a17bc0)
nakama_1       |        runtime/panic.go:965 +0x1b9
nakama_1       | github.com/dop251/goja.(*vm).try.func1(0xc000b46e00, 0x0, 0xc0010ca880, 0x0, 0x0, 0x0, 0xc0010ca918)
nakama_1       |        github.com/dop251/goja@v0.0.0-20210406175830-1b11a6af686d/vm.go:505 +0xc1d
nakama_1       | panic(0x1b4eac0, 0x2a17bc0)
nakama_1       |        runtime/panic.go:965 +0x1b9
nakama_1       | github.com/dop251/goja.(*vm).try.func1(0xc000b46e00, 0x2, 0xc0010ca540, 0xd, 0x0, 0x0, 0xc0010ca5d8)
nakama_1       |        github.com/dop251/goja@v0.0.0-20210406175830-1b11a6af686d/vm.go:505 +0xc1d
nakama_1       | panic(0x1b4eac0, 0x2a17bc0)
nakama_1       |        runtime/panic.go:965 +0x1b9
nakama_1       | github.com/dop251/goja.(*vm).try.func1(0xc000b46e00, 0x4, 0xc0010c9f28, 0x18, 0x0, 0x0, 0xc0010c9fc0)
nakama_1       |        github.com/dop251/goja@v0.0.0-20210406175830-1b11a6af686d/vm.go:505 +0xc1d
nakama_1       | panic(0x1b4eac0, 0x2a17bc0)
nakama_1       |        runtime/panic.go:965 +0x1b9
nakama_1       | github.com/heroiclabs/nakama/v3/server.(*runtimeJavascriptNakamaModule).matchGet.func1(0x2211c18, 0xc000214e70, 0xc001302c20, 0x1, 0x1e, 0x9a97dd, 0xc000043125)
nakama_1       |        github.com/heroiclabs/nakama/v3/server/runtime_javascript_nakama.go:2722 +0x10a
nakama_1       | github.com/dop251/goja.(*vm)._nativeCall(0xc000b46e00, 0xc000378240, 0x1)
nakama_1       |        github.com/dop251/goja@v0.0.0-20210406175830-1b11a6af686d/vm.go:2357 +0x266
nakama_1       | github.com/dop251/goja.call.exec(0x1, 0xc000b46e00)
nakama_1       |        github.com/dop251/goja@v0.0.0-20210406175830-1b11a6af686d/vm.go:2329 +0x776
nakama_1       | github.com/dop251/goja.(*vm).run(0xc000b46e00)
nakama_1       |        github.com/dop251/goja@v0.0.0-20210406175830-1b11a6af686d/vm.go:395 +0x94
nakama_1       | github.com/dop251/goja.(*vm).try(0xc000b46e00, 0xc0010ca020, 0x0)
nakama_1       |        github.com/dop251/goja@v0.0.0-20210406175830-1b11a6af686d/vm.go:511 +0x188
nakama_1       | github.com/dop251/goja.(*vm).runTry(...)
nakama_1       |        github.com/dop251/goja@v0.0.0-20210406175830-1b11a6af686d/vm.go:516
nakama_1       | github.com/dop251/goja.try.exec(0x13, 0xc000b46e00)
...
```
## Context
- [X] Typescript runtime

## Your Environment
- Nakama: 3.2.1+6790d453
- Database: v20.2.5
- Environment name and version: Typescript
- Operating System and version: Windows

**Comment by Meneleus** [comment]
The fix makes it so that this no longer crashes. However, I expected an exception to be thrown since after this fix I am returned a null match. Which breaks the signature of the method, matchGet **must** return a Match. (Either it needs to be Match|null or you need to throw an error.) I _think_...

**Comment by sesposito** [comment]
You're correct, I've fixed the TS function return types on nakama-common's master. The expected behaviour is for the function to return null if the match is not found.

**Comment by Meneleus** [comment]
That works for me. I'll update my typedef to match for now.
