### ISSUE TITLE
Panic on registerRpc if class instance method called before

### ISSUE THREAD

**Issue by vyacheslav-sozap** [heroiclabs/nakama#724]
## Description
Runtime: JavaScript. Panic in registerRpc in case of call to class instance method previously.

## Steps to Reproduce
Build and run Nakama with following TypeScript module code:

```
class Test {
    test() {
    }
}

let TEST_RPC: nkruntime.RpcFunction = function (ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
    return 'none';
}

let InitModule: nkruntime.InitModule = function (
    ctx: nkruntime.Context,
    logger: nkruntime.Logger,
    nk: nkruntime.Nakama,
    initializer: nkruntime.Initializer
) {
    (new Test()).test();

    initializer.registerRpc('TEST_RPC', TEST_RPC);
}
```

## Expected Result
Nakama will run.

## Actual Result
Nakama will crash with error:

```
panic: interface conversion: ast.Expression is *ast.NewExpression, not *ast.Identifier [recovered]
  panic: interface conversion: ast.Expression is *ast.NewExpression, not *ast.Identifier [recovered]
  panic: interface conversion: ast.Expression is *ast.NewExpression, not *ast.Identifier
goroutine 1 [running]:
github.com/dop251/goja.AssertFunction.func1.1()
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/runtime.go:2162 +0x74
panic({0x1882f80, 0xc0001df6e0})
  runtime/panic.go:1038 +0x215
github.com/dop251/goja.(*vm).try.func1()
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/vm.go:512 +0x8eb
panic({0x1882f80, 0xc0001df6e0})
  runtime/panic.go:1038 +0x215
github.com/heroiclabs/nakama/v3/server.(*RuntimeJavascriptInitModule).getRpcFnIdentifier(0xc00005b000, 0xc00051b6f8, 0x0, {0xc00076a521, 0xc0007a6228}, {0xc0002a2e40, 0x18})
  github.com/heroiclabs/nakama/v3/server/runtime_javascript_init.go:312 +0x4ef
github.com/heroiclabs/nakama/v3/server.(*RuntimeJavascriptInitModule).extractRpcFn(0x1e8f0d8, 0xc0001df290, {0xc0002a2e40, 0x8})
  github.com/heroiclabs/nakama/v3/server/runtime_javascript_init.go:292 +0x71
github.com/heroiclabs/nakama/v3/server.(*RuntimeJavascriptInitModule).registerRpc.func1({{0x1e8f0d8, 0xc0007d6ea0}, {0xc000192a40, 0x2, 0x4}})
  github.com/heroiclabs/nakama/v3/server/runtime_javascript_init.go:273 +0x210
github.com/dop251/goja.(*vm)._nativeCall(0xc0004ead00, 0xc0007deb40, 0x2)
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/vm.go:2658 +0x223
github.com/dop251/goja.call.exec(0x8, 0xc0004ead00)
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/vm.go:2630 +0x81b
github.com/dop251/goja.(*vm).run(0xc0004ead00)
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/vm.go:402 +0x8b
github.com/dop251/goja.(*baseJsFuncObject)._call(0xc000012580, {{0x1e8f890, 0x29845c0}, {0xc0002833c0, 0x4, 0x4}}, {0x0, 0x0}, {0x1e8f890, 0x29845c0})
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/func.go:172 +0x2d8
github.com/dop251/goja.(*funcObject).call(...)
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/func.go:180
github.com/dop251/goja.(*funcObject).Call(0xc0001df350, {{0x1e8f890, 0x29845c0}, {0xc0002833c0, 0x4, 0x4}})
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/func.go:140 +0xc9
github.com/dop251/goja.AssertFunction.func1.2()
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/runtime.go:2167 +0x7d
github.com/dop251/goja.(*vm).try(0x962454, 0x0)
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/vm.go:518 +0x1a4
github.com/dop251/goja.AssertFunction.func1({0x1e8f890, 0x29845c0}, {0xc0002833c0, 0x8, 0xc0000120b0})
  github.com/dop251/goja@v0.0.0-20211022113120-dc8c55024d06/runtime.go:2166 +0x110
github.com/heroiclabs/nakama/v3/server.evalRuntimeModules(0xc0004eac00, 0xc000047600, 0xc0005384b0, {0x1e74cf8, 0xc0000120b0}, 0x2, 0xc000521200, 0x0)
  github.com/heroiclabs/nakama/v3/server/runtime_javascript.go:1960 +0x75c
github.com/heroiclabs/nakama/v3/server.NewRuntimeProviderJS(_, _, _, _, _, {_, _}, _, {0x1e8a060, 0xc000520300}, ...)
  github.com/heroiclabs/nakama/v3/server/runtime_javascript.go:623 +0xb4d
github.com/heroiclabs/nakama/v3/server.NewRuntime({0x1e6d230, 0xc00017d140}, 0xc000080c00, 0xc000080c00, 0xc00017eea0, 0x273d5e0, 0x294cd80, {0x1e901d8, 0xc000012160}, 0xc00055a0a0, ...)
  github.com/heroiclabs/nakama/v3/server/runtime.go:595 +0xdcb
main.main()
  main.go:144 +0x149d
```

## Your Environment
- Nakama: 3.9.0
- Database: PostgreSQL from Docker image postgres:14.1-alpine
- Environment name and version: Docker image heroiclabs/nakama:3.9.0
- Operating System and version: WSL2 on Windows 10

**Comment by novabyte** [comment]
Thanks @vyacheslav-sozap. Could you move the TEST_RPC function to be defined within the InitModule function and test again for us?

**Comment by vyacheslav-sozap** [comment]
Sure, this way

```
class Test {
    test() {
    }
}

let InitModule: nkruntime.InitModule = function (
    ctx: nkruntime.Context,
    logger: nkruntime.Logger,
    nk: nkruntime.Nakama,
    initializer: nkruntime.Initializer
) {
    let TEST_RPC: nkruntime.RpcFunction = function (ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
        return 'none';
    };

    (new Test()).test();

    initializer.registerRpc('TEST_RPC', TEST_RPC);
}
```

It still crashes with the same message.

For myself, I currently found workaround:

```
class Test {
    test() {
    }
}

let InitModule: nkruntime.InitModule = function (
    ctx: nkruntime.Context,
    logger: nkruntime.Logger,
    nk: nkruntime.Nakama,
    initializer: nkruntime.Initializer
) {
    let TEST_RPC: nkruntime.RpcFunction = function (ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
        return 'none';
    };

    (function () {
        (new Test()).test();
    })();

    initializer.registerRpc('TEST_RPC', TEST_RPC);
}
```
