### ISSUE TITLE
Nakama service gets terminated

### ISSUE THREAD

**Issue by Ali1Abbas** [heroiclabs/nakama#969]
our project currently live and we have a problem with the nakama service getting terminated we have checked Nakama catches this error :
net/http. (*connReader).Read(0xc000b23b.
8]: net/http/server.go: 780 +0x16d
8]: bufio.(*Reader) .£i11(0xc0009c0f00)
8]: bufio/bufio.go: 106 +0x103
8]: bufio.( *Reader).Peek(0xco009c0fo0, 0x4)
8]: bufio/bu£io.go:144.+0x5d
8]: net/http.(*conn).serve( 0xc0009 743c0, (0
78]: net/http/server.go:1992 +0x716
78]: created by net/http. (*Server) .Serve
78]:. net/http/server.go:3071 +0x4db

we have realized that a fatal error occur in the go build in Nakama it seem mutex happed 2 goroutines try to reach the same resource at the same time and race condition happened.
 
We have checked server log nakam fatal error concurrent  map write after that Nakama catch this exception 
 
Server log :
 
 
 
github.com/heroiclabs/nakama/v3/server.NewRuntimeEventQueue.func1()
nakama: github.com/heroiclabs/nakama/v3/server/runtime_event.go:46 +0x92
nakama: created by github.com/heroiclabs/nakama/v3/server.NewRuntimeEventQueue
nakama: github.com/heroiclabs/nakama/v3/server/runtime_event.go:44 +0x117
nakama: goroutine 382027 [IO wait]:
nakama: internal/poll.runtime_pollWait(0x7f0df2b1c9f0, 0x72)
nakama: runtime/netpoll.go:302 +0x89
nakama: internal/poll.(*pollDesc).wait(0xc000df6580?, 0xc00019c000?, 0x0)
nakama: internal/poll/fd_poll_runtime.go:83 +0x32
nakama: internal/poll.(*pollDesc).waitRead(...)
nakama: internal/poll/fd_poll_runtime.go:88
nakama: internal/poll.(*FD).Read(0xc000df6580, {0xc00019c000, 0x1000, 0x1000})
                                                                                                                              
 
 
nakama: goroutine 84 [select, 1 minutes]:
nakama: github.com/blugelabs/bluge/index.analysisWorker(0xc0004c04e0, 0xc0004c0540)
nakama: github.com/blugelabs/bluge@v0.1.9/index/writer.go:549 +0x7f
nakama: github.com/blugelabs/bluge/index.OpenWriter.func1()
nakama: github.com/blugelabs/bluge@v0.1.9/index/writer.go:69 +0x2f
nakama: created by github.com/blugelabs/bluge/index.defaultConfig.func2
nakama: github.com/blugelabs/bluge@v0.1.9/index/config.go:205 +0x19
nakama: goroutine 85 [select, 1 minutes]:
nakama: github.com/blugelabs/bluge/index.analysisWorker(0xc0004c04e0, 0xc0004c0540)
nakama: github.com/blugelabs/bluge@v0.1.9/index/writer.go:549 +0x7f
nakama: github.com/blugelabs/bluge/index.OpenWriter.func1()
nakama: github.com/blugelabs/bluge@v0.1.9/index/writer.go:69 +0x2f
nakama: created by github.com/blugelabs/bluge/index.defaultConfig.func2
nakama: github.com/blugelabs/bluge@v0.1.9/index/config.go:205 +0x19
nakama: goroutine 86 [select]:
<img width="534" alt="nakama1" src="https://user-images.githubusercontent.com/81974420/211998063-482033a7-686c-48b8-bdf0-5507d214ed2e.PNG">

**Comment by mofirouz** [comment]
GitHub issues are not the right place to ask community questions. However I already know you’ve posted on the forums, sent the team various DMs, and sent Heroic multiple emails. I’m locking this issue as spam at this stage. 

This is not a Nakama issue.
